# -*- mode: ruby -*-
# vi: set ft=ruby :

# vagrant up --provider=hyperv

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.box_download_insecure = true
  config.vm.synced_folder "../", "/vagrant_src"
end